# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llbR1_j <- function(betajk_j, sjk2_j, tau2inv) {
    .Call('_mamba_llbR1_j', PACKAGE = 'mamba', betajk_j, sjk2_j, tau2inv)
}

logsumexp <- function(x) {
    .Call('_mamba_logsumexp', PACKAGE = 'mamba', x)
}

llb0_ab <- function(betajk, sjk2, lambda, alpha) {
    .Call('_mamba_llb0_ab', PACKAGE = 'mamba', betajk, sjk2, lambda, alpha)
}

llbR0_j <- function(betajk_j, sjk2_j, lambda, alpha) {
    .Call('_mamba_llbR0_j', PACKAGE = 'mamba', betajk_j, sjk2_j, lambda, alpha)
}

deltis <- function(betajk_j, sjk2_j, lambda, alpha) {
    .Call('_mamba_deltis', PACKAGE = 'mamba', betajk_j, sjk2_j, lambda, alpha)
}

rcpp_hello_world <- function() {
    .Call('_mamba_rcpp_hello_world', PACKAGE = 'mamba')
}

