# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llbR1_i <- function(betaij_i, sij2_i, tau2inv) {
    .Call(`_emfuncs_llbR1_i`, betaij_i, sij2_i, tau2inv)
}

logsumexp <- function(x) {
    .Call(`_emfuncs_logsumexp`, x)
}

llb0_ab <- function(betaij, sij2, f, alpha) {
    .Call(`_emfuncs_llb0_ab`, betaij, sij2, f, alpha)
}

llbR0_i <- function(betaij_i, sij2_i, f, alpha) {
    .Call(`_emfuncs_llbR0_i`, betaij_i, sij2_i, f, alpha)
}

deltis <- function(betaij_i, sij2_i, f, alpha) {
    .Call(`_emfuncs_deltis`, betaij_i, sij2_i, f, alpha)
}

rcpp_hello_world <- function() {
    .Call(`_emfuncs_rcpp_hello_world`)
}

